#!/bin/sh

## Create the temporary directory 
mkdir -p ~/.google-docs-fs/

## Mount the file system
if [ $# -ne 2 ]
	then
	echo "Usage: gmount [mountpoint] [googlemail]"
else
    ./"gFile.py" $2 $1
        
fi

