#!/bin/bash

if [ $# -ne 2 ]
	then
	echo "Usage: gmount [mountpoint] [googlemail]"
else
	echo "Enter password for " $2 ":"
	read -s pass
    ./"gFile.py" $2 $pass $1
        
fi

## Create the temporary directory 
mkdir -p /tmp/google-docs-fs 
